apiVersion: v1
kind: Service
metadata:
  name: commercial-manager-service-dev
spec:
  selector:
    app: commercial-manager-dev
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
